//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fallen8.API.Service.REST.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Frontend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frontend() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fallen8.API.Service.REST.Ressource.Frontend", typeof(Frontend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showLogo();
        ///	showCopyright();
        ///	showStatus();
        ///	&lt;/script&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Fallen-8&lt;/title&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;Frontend/Ressource/d3.v2.js&quot;&gt;&lt;/script&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;Frontend/Ressource/copyright.js&quot;&gt;&lt;/script&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;Frontend/Ressource/logo.js&quot;&gt;&lt;/script&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;Frontend/Ressource/status.js&quot;&gt;&lt;/script&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///line {
        ///  stroke: rgba(32,32,32,3.3);
        ///}
        ///
        ///text {
        ///  font: 10px sans-serif;
        ///  pointer-events: none;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pre {
            get {
                return ResourceManager.GetString("Pre", resourceCulture);
            }
        }
    }
}
